"""add prompt_executions table

Revision ID: 3b1bbefb4e73
Revises: 3686d8f6d714
Create Date: 2026-08-08 10:55:16.040106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1bbefb4e73'
down_revision: Union[str, None] = '3686d8f6d714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_executions',
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_executions_id'), 'prompt_executions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_executions_prompt_id'), 'prompt_executions', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompt_executions_user_id'), 'prompt_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_executions_user_id'), table_name='prompt_executions')
    op.drop_index(op.f('ix_prompt_executions_prompt_id'), table_name='prompt_executions')
    op.drop_index(op.f('ix_prompt_executions_id'), table_name='prompt_executions')
    op.drop_table('prompt_executions')
    # ### end Alembic commands ###
